version: "3.8"

services:
  notes-service:
    build:
      context: ../../services/notes-service
      dockerfile: ../../infra/docker/notes-service/Dockerfile
    ports:
      - "8080:8080"
    container_name: notes-service
