version: "3.8"

services:
  notes-service:
    build:
      context: ../../services/notes-service
      dockerfile: ../../infra/docker/notes-service/Dockerfile
    ports:
      - "8080:8080"
    container_name: notes-service

  sql-service:
    image: postgres:15
    container_name: sql-service
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
