spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate # Ensures schema validation without automatic updates. Use migration tools like Flyway or Liquibase for schema changes.
    show-sql: true
