name: Note Service

on:
  push:
    branches:
      - "feature/**" # only run on feature branches

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "24"
          cache: "maven"

      - name: Run Unit Tests (Note Service)
        run: mvn -B test --file services/note-service/pom.xml
