name: Note Service Unit Tests

on:
  push:
    branches:
      - "feature/**" # only run on feature branches

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "24"
          cache: "maven"

      - name: Make mvnw executable
        run: chmod +x services/note-service/mvnw

      - name: Run Unit Tests (Note Service)
        run: |
          cd services/note-service
          ./mvnw -B clean test -U
